### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by danielstankw** [vincrichard/UnsupervisedAnomalyDetection_Timeseries#2]
Hi :) 
Thank you for sharing your work it is very helpful, 
I am working on very similar project with Tensorflow instead of Pytorch.
I have encountered some difficulties related to real-time predictions would you be available for some questions? 
Is there any way I could contact you privately?

**Comment by vincrichard** [comment]
Hello,
I am afraid this was purely a student project. In that sense, I never had to run real-time predictions. It's been a couple years since I did this project, but if I remember correctly the preprocessing is quite heavy. I was computing 10 features with tsfeatures, I guess this preprocessing is not viable in a real-time scenario.

I will answer any questions you may have here, but I don't see the use of going through emails.
